require File.expand_path(File.dirname(__FILE__) + '/../spec_helper')
require 'rubygems'

describe AssetController do
  
   describe "Paths Generated by Custom Routes:" do
     it "should map {:controller => 'asset', :action => 'show', :id => '555' }" do
        expect({ :get => "/assets/555" }).to route_to(:controller => 'asset', :action => 'show', :id => '555')
     end 
     
      it "should map {:controller => 'asset', :action => 'show_page', :id => '555', :page => '1234' }" do
         expect({ :get => "/assets/555/1234" }).to route_to(:controller => 'asset', :action => 'show_page', :id => '555', :page => '1234')
      end
      
   end
  
  
end